name: infomentor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.1
  video_player: ^2.6.1
  chewie: ^1.5.0
  youtube_player_flutter: ^8.1.2
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  file_picker: ^5.3.3
  cloud_functions: ^4.3.4
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.8
  g_recaptcha_v3: ^0.0.5
  google_fonts: ^6.1.0

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/testAnswer.png
    - assets/placeholder.png
    - assets/profilePicture.svg
    - assets/logo.svg
    - assets/logoFilled.svg
    - assets/background.svg
    - assets/lastScreenBackground.svg
    - assets/star.svg
    - assets/badges/
    - assets/graphs/
    - assets/avatars/
    - assets/icons/
    - assets/tutorial/
    - assets/roadmap/
    - assets/bottomBackground.svg
    - assets/notifications/
