name: infomentor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  cloud_functions: ^4.4.1
  video_player: ^2.6.1
  chewie: ^1.5.0
  youtube_player_flutter: ^8.1.2
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.8
  g_recaptcha_v3: ^0.0.5
  google_fonts: ^6.1.0
  flutter_styled_toast: ^2.2.1
  flutter_gcaptcha_v3: ^2.0.4
  excel: ^3.0.0
  csv: ^5.1.1
  mailer: ^6.0.1
  smtpd: ^0.2.0
  image_picker_web: ^3.1.1
  firebase_storage: ^11.2.8
  uuid: ^4.1.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/testAnswer.png
    - assets/skoly.txt
    - assets/placeholder.png
    - assets/profilePicture.svg
    - assets/logo.svg
    - assets/import.png
    - assets/logoFilled.svg
    - assets/background.svg
    - assets/lastScreenBackground.svg
    - assets/star.png
    - assets/badges/
    - assets/pictures/
    - assets/pictureAnswers/
    - assets/avatars/
    - assets/icons/
    - assets/tutorial/
    - assets/roadmap/
    - assets/bottomBackground.svg
    - assets/notifications/
    - assets/learningCards/
