// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxORmtJ4yQBMBT87i1tQiw1675VM39II',
    appId: '1:383337818314:web:a6e8c3e5cd1323fee1ac33',
    messagingSenderId: '383337818314',
    projectId: 'infomentor-d71f7',
    authDomain: 'infomentor-d71f7.firebaseapp.com',
    storageBucket: 'infomentor-d71f7.appspot.com',
    measurementId: 'G-DF2Y7P0QX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJBvVIUoxpnvSzDy2JoClW09vSNYViQR4',
    appId: '1:383337818314:android:092717513e3b0f71e1ac33',
    messagingSenderId: '383337818314',
    projectId: 'infomentor-d71f7',
    storageBucket: 'infomentor-d71f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDxtOkvDC4ppotKmwKT6OVXEA3AzBxkGM',
    appId: '1:383337818314:ios:33391e13675634cee1ac33',
    messagingSenderId: '383337818314',
    projectId: 'infomentor-d71f7',
    storageBucket: 'infomentor-d71f7.appspot.com',
    iosClientId: '383337818314-pllnhnv6ss10o5872a6b88uq2m07h0rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.infomentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDxtOkvDC4ppotKmwKT6OVXEA3AzBxkGM',
    appId: '1:383337818314:ios:8aea207778ab05c9e1ac33',
    messagingSenderId: '383337818314',
    projectId: 'infomentor-d71f7',
    storageBucket: 'infomentor-d71f7.appspot.com',
    iosClientId: '383337818314-dmrgcqemrbaouracpopgi6i7h8apbtt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.infomentor.RunnerTests',
  );
}
